#!/bin/bash

echo ""
echo "EasyNOMP Committing all changes/files to Git..."
echo ""

source ~/.bashrc
source /etc/os-release

## who am i? ##
SCRIPTNAME="$(readlink -f ${BASH_SOURCE[0]})"
BASEDIR="$(dirname $SCRIPTNAME)"
GITPRJDIR=$(git rev-parse --show-toplevel)
RELIN=$(realpath --relative-to="${GITPRJDIR}" "${1}")

## Okay, print it ##
echo "Script name : $SCRIPTNAME"
echo "Current working dir : $PWD"
echo "Script location path (dir) : $BASEDIR"
echo "Git repo location path (dir) : $GITPRJDIR"
echo "INPUT: ${RELIN}"
echo ""

if [ ! -z $GITPRJDIR ]; then
    
        cd ${GITPRJDIR};    
    
        # Add to git commit
        git add *
        git commit -am "${1}" ;
        echo "";
        git push
        echo "";
        echo "";
        echo "I've successfully updated the commit with message [${1}]!";
        
        cd ${pwd}; 
    
else

    # Add to git ignore
    echo "This location is not a git repo!"; 
 
fi


echo ""
echo "Done!"
echo ""

exit 0
